# Generated by Django 4.0.1 on 2022-02-23 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_emailsettings_history_task_priority_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='email_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
